---
Name: imagecropfield
After:
  - "assetsimage"
---
SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - WebbuildersGroup\ImageCropField\Extensions\ImageCropFieldAssetFormFactoryExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - "vendor/webbuilders-group/silverstripe-image-cropper-field/javascript/boot/boot.js"