---
Name: imagecropfield
After:
  - "assetsimage"
---
SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - WebbuildersGroup\ImageCropField\Extensions\ImageCropFieldAssetFormFactoryExtension
